import {
  MenuArrow,
  MenuBackdrop,
  MenuGroup,
  MenuGroupLabel,
  MenuItem,
  MenuLinkItem,
  MenuPopup,
  MenuPortal,
  MenuPositioner,
  MenuRoot,
  MenuSeparator,
  MenuTrigger,
} from "./menu"

export {
  MenuArrow,
  type MenuArrowProps,
  MenuBackdrop,
  type MenuBackdropProps,
  MenuGroup,
  MenuGroupLabel,
  type MenuGroupLabelProps,
  type MenuGroupProps,
  MenuItem,
  type MenuItemProps,
  MenuLinkItem,
  type MenuLinkItemProps,
  MenuPopup,
  type MenuPopupProps,
  MenuPortal,
  type MenuPortalProps,
  MenuPositioner,
  type MenuPositionerProps,
  MenuRoot,
  type MenuRootProps,
  MenuSeparator,
  type MenuSeparatorProps,
  MenuTrigger,
  type MenuTriggerProps,
} from "./menu"

export const Menu = {
  Arrow: MenuArrow,
  Backdrop: MenuBackdrop,
  Group: MenuGroup,
  GroupLabel: MenuGroupLabel,
  Item: MenuItem,
  LinkItem: MenuLinkItem,
  Popup: MenuPopup,
  Portal: MenuPortal,
  Positioner: MenuPositioner,
  Root: MenuRoot,
  Separator: MenuSeparator,
  Trigger: MenuTrigger,
} as const
